{
  "formatVersion": "1.1",
  "component": {
    "group": "com.x930073498.component",
    "module": "auto",
    "version": "0.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "cjpe3eq5frdx7lai3z6ezy2ewe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "auto-0.0.9.jar",
          "url": "auto-0.0.9.jar",
          "size": 1770,
          "sha512": "092a869543ef0c196c19a001d3cc6ded0ccf48ed142e08bba3fbc2aa5d86916f5e778dc2d366984c2e4b1a2dd7c4b5345138bdc3c2307889a73f4190f1c7859b",
          "sha256": "637c92d741e50a31f347ba7037bd7afafd6d0106207e532f860ba58e7ac32020",
          "sha1": "1997ff39a08ddec8e2ed12702f7b81444a337f1f",
          "md5": "c6952a473e51f18ff535add9bd502958"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "auto-0.0.9.jar",
          "url": "auto-0.0.9.jar",
          "size": 1770,
          "sha512": "092a869543ef0c196c19a001d3cc6ded0ccf48ed142e08bba3fbc2aa5d86916f5e778dc2d366984c2e4b1a2dd7c4b5345138bdc3c2307889a73f4190f1c7859b",
          "sha256": "637c92d741e50a31f347ba7037bd7afafd6d0106207e532f860ba58e7ac32020",
          "sha1": "1997ff39a08ddec8e2ed12702f7b81444a337f1f",
          "md5": "c6952a473e51f18ff535add9bd502958"
        }
      ]
    }
  ]
}
