{
  "formatVersion": "1.1",
  "component": {
    "group": "com.x930073498.component",
    "module": "router-annotations",
    "version": "0.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "cjpe3eq5frdx7lai3z6ezy2ewe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "router-annotations-0.0.9.jar",
          "url": "router-annotations-0.0.9.jar",
          "size": 11281,
          "sha512": "f04187b8c3d9ef3d0f967d4015439ab5efb96f30ab37e8350de2d3b820cab90505ef0d357182a01de6358ceef0751e944d8c2e6895162c6bb65055c5e5795fe5",
          "sha256": "18ae0da8bcc6b6270fea1a830ec3e279ebfd057daacf05311d201bed500ea6be",
          "sha1": "835cdb888701941a987a3cdbf3ceab18d2c840c3",
          "md5": "f22a5bf7f6592206def895ddf9957908"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "router-annotations-0.0.9.jar",
          "url": "router-annotations-0.0.9.jar",
          "size": 11281,
          "sha512": "f04187b8c3d9ef3d0f967d4015439ab5efb96f30ab37e8350de2d3b820cab90505ef0d357182a01de6358ceef0751e944d8c2e6895162c6bb65055c5e5795fe5",
          "sha256": "18ae0da8bcc6b6270fea1a830ec3e279ebfd057daacf05311d201bed500ea6be",
          "sha1": "835cdb888701941a987a3cdbf3ceab18d2c840c3",
          "md5": "f22a5bf7f6592206def895ddf9957908"
        }
      ]
    }
  ]
}
