{
  "formatVersion": "1.1",
  "component": {
    "group": "Component",
    "module": "auto-plugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "ulj5demojvcr5mz277alrbmipe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.x930073498.component",
          "module": "auto",
          "version": {
            "requires": "+"
          }
        }
      ],
      "files": [
        {
          "name": "auto-plugin-0.0.15.jar",
          "url": "auto-plugin-0.0.15.jar",
          "size": 139367,
          "sha512": "852ed1c93f52ba387966cda1bd6838dc4d74b0be242b15398eed741350eb5a73a57b01c493c0ad6c20c4af4d17186dc825465f0f02ddb64a8d96b9692a4cc24c",
          "sha256": "8fe32da31dedfbd24791f1ee9108f2e1430f17d2b338db4e749bfede2d900a57",
          "sha1": "a6f0995218ec5e037eaab438e02d9028b6db31e6",
          "md5": "b047a53735af3200f4c7aa2afcd5b645"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "3.6.3"
          }
        },
        {
          "group": "org.jacoco",
          "module": "org.jacoco.core",
          "version": {
            "requires": "0.8.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "com.x930073498.component",
          "module": "auto",
          "version": {
            "requires": "+"
          }
        }
      ],
      "files": [
        {
          "name": "auto-plugin-0.0.15.jar",
          "url": "auto-plugin-0.0.15.jar",
          "size": 139367,
          "sha512": "852ed1c93f52ba387966cda1bd6838dc4d74b0be242b15398eed741350eb5a73a57b01c493c0ad6c20c4af4d17186dc825465f0f02ddb64a8d96b9692a4cc24c",
          "sha256": "8fe32da31dedfbd24791f1ee9108f2e1430f17d2b338db4e749bfede2d900a57",
          "sha1": "a6f0995218ec5e037eaab438e02d9028b6db31e6",
          "md5": "b047a53735af3200f4c7aa2afcd5b645"
        }
      ]
    }
  ]
}
