{
  "formatVersion": "1.1",
  "component": {
    "group": "com.x930073498.component",
    "module": "auto-plugin",
    "version": "0.0.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "oyudhpefeza2vm4iz7mydkidh4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "auto-plugin-0.0.18.jar",
          "url": "auto-plugin-0.0.18.jar",
          "size": 139367,
          "sha512": "8a8f27ef7d2fef2ed25612fc9527827a63043c031106f0f2f6d78f55710b931f8f97e95a3af6dcd84e7c7587e8d1fb516cb80455e73b050d7b634d6dd6e05af4",
          "sha256": "1fd924a2446f4c7da073a4704cfee4c7472c017f821e7d63de6d31eed3a10cd3",
          "sha1": "e77405b1ca34ce0ebe9c22a6ccc8279a98f78155",
          "md5": "8b6f7f064385459d4d71c704aadec457"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "3.6.3"
          }
        },
        {
          "group": "org.jacoco",
          "module": "org.jacoco.core",
          "version": {
            "requires": "0.8.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "auto-plugin-0.0.18.jar",
          "url": "auto-plugin-0.0.18.jar",
          "size": 139367,
          "sha512": "8a8f27ef7d2fef2ed25612fc9527827a63043c031106f0f2f6d78f55710b931f8f97e95a3af6dcd84e7c7587e8d1fb516cb80455e73b050d7b634d6dd6e05af4",
          "sha256": "1fd924a2446f4c7da073a4704cfee4c7472c017f821e7d63de6d31eed3a10cd3",
          "sha1": "e77405b1ca34ce0ebe9c22a6ccc8279a98f78155",
          "md5": "8b6f7f064385459d4d71c704aadec457"
        }
      ]
    }
  ]
}
