{
  "formatVersion": "1.1",
  "component": {
    "group": "Component",
    "module": "auto-plugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "f36m5rye6fb45miufpzl66dshq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "auto-plugin-0.0.11.jar",
          "url": "auto-plugin-0.0.11.jar",
          "size": 106277,
          "sha512": "3e1b7837d8083414f5f99dcc5df5ac24a67e549358eab810866e145e240e5bef111e6bf4c7922a6ee94a8abed2b73a134401d74f09497791f6df6a2aaa65b42c",
          "sha256": "3496f461dda63b1813bbdbc6e39bf66f96eb7595960367ef58ffe626068e863b",
          "sha1": "7cfc1fe7ecbe5f961e69655f86338eb92f695d9b",
          "md5": "c34382653f0dd23466f2ae0ab8e574f8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "3.6.3"
          }
        },
        {
          "group": "org.jacoco",
          "module": "org.jacoco.core",
          "version": {
            "requires": "0.8.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "auto-plugin-0.0.11.jar",
          "url": "auto-plugin-0.0.11.jar",
          "size": 106277,
          "sha512": "3e1b7837d8083414f5f99dcc5df5ac24a67e549358eab810866e145e240e5bef111e6bf4c7922a6ee94a8abed2b73a134401d74f09497791f6df6a2aaa65b42c",
          "sha256": "3496f461dda63b1813bbdbc6e39bf66f96eb7595960367ef58ffe626068e863b",
          "sha1": "7cfc1fe7ecbe5f961e69655f86338eb92f695d9b",
          "md5": "c34382653f0dd23466f2ae0ab8e574f8"
        }
      ]
    }
  ]
}
