{
  "formatVersion": "1.1",
  "component": {
    "group": "Component",
    "module": "auto-plugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "xx6sahnj3zbwpiztlhlw664bau"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "auto-plugin-0.0.9.jar",
          "url": "auto-plugin-0.0.9.jar",
          "size": 77447,
          "sha512": "0d0f745eac04a46578f8336c9425114293b5562c8b63cd9c199517fb767add301bf917dc330c7ca8efe1fdb16ba75215f7cbc256d2f1845f723d8bc5822df75f",
          "sha256": "5290808b7d1e38552c4d57ea02a5e2b7def3744af2f1581197598ec31aff25c3",
          "sha1": "154a4309f486dd11332a9d7b73c1f84c2ff49812",
          "md5": "f83ee27b11ba8719b16fa790af742b28"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "3.6.3"
          }
        },
        {
          "group": "org.jacoco",
          "module": "org.jacoco.core",
          "version": {
            "requires": "0.8.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "auto-plugin-0.0.9.jar",
          "url": "auto-plugin-0.0.9.jar",
          "size": 77447,
          "sha512": "0d0f745eac04a46578f8336c9425114293b5562c8b63cd9c199517fb767add301bf917dc330c7ca8efe1fdb16ba75215f7cbc256d2f1845f723d8bc5822df75f",
          "sha256": "5290808b7d1e38552c4d57ea02a5e2b7def3744af2f1581197598ec31aff25c3",
          "sha1": "154a4309f486dd11332a9d7b73c1f84c2ff49812",
          "md5": "f83ee27b11ba8719b16fa790af742b28"
        }
      ]
    }
  ]
}
