{
  "formatVersion": "1.1",
  "component": {
    "group": "Component",
    "module": "auto-plugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "wc3kbwncevczzio3tjqepyb4hq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "auto-plugin-0.0.9.jar",
          "url": "auto-plugin-0.0.9.jar",
          "size": 75251,
          "sha512": "ea3df84eefa790c2bff1f6ff0f82f79176304b322b296c23488e28908cee62cefb8e1a6be7c08805a4d7eaa68081298bba5a591d347433d1c7642c5dcee11e0b",
          "sha256": "49d3836b0401f170996d221897da8c10935a32e98c405351254a21b683068580",
          "sha1": "7cc92fa02a27118dec69368110858da75b87932a",
          "md5": "7ecb49ab9b01b8d78c8d0d46c7e36b6f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "3.6.3"
          }
        },
        {
          "group": "org.jacoco",
          "module": "org.jacoco.core",
          "version": {
            "requires": "0.8.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "auto-plugin-0.0.9.jar",
          "url": "auto-plugin-0.0.9.jar",
          "size": 75251,
          "sha512": "ea3df84eefa790c2bff1f6ff0f82f79176304b322b296c23488e28908cee62cefb8e1a6be7c08805a4d7eaa68081298bba5a591d347433d1c7642c5dcee11e0b",
          "sha256": "49d3836b0401f170996d221897da8c10935a32e98c405351254a21b683068580",
          "sha1": "7cc92fa02a27118dec69368110858da75b87932a",
          "md5": "7ecb49ab9b01b8d78c8d0d46c7e36b6f"
        }
      ]
    }
  ]
}
