{
  "formatVersion": "1.1",
  "component": {
    "group": "Component",
    "module": "auto-plugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "5neokztq5rbodfvyo7g3owyipi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "auto-plugin-unspecified.jar",
          "url": "auto-plugin-unspecified.jar",
          "size": 146390,
          "sha512": "40c4fe0826980e745b2053aa1f7a5ac57dcbd808b2bb116d0877215b9b761e9d29fb64c4cc3eb8092328abf372ac9d5bae5a4a1566dd387d73d188d9c0705dc2",
          "sha256": "67fc7de273669c3a3265b5a8d3f3fa7abd8f941ddc58462b89927afcdc1d5b0a",
          "sha1": "94e3b8a5fdca0682430f6c8c20b791732124d473",
          "md5": "7bdcb268e2c901e939a972d2e21262f1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "3.6.3"
          }
        },
        {
          "group": "org.jacoco",
          "module": "org.jacoco.core",
          "version": {
            "requires": "0.8.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "auto-plugin-unspecified.jar",
          "url": "auto-plugin-unspecified.jar",
          "size": 146390,
          "sha512": "40c4fe0826980e745b2053aa1f7a5ac57dcbd808b2bb116d0877215b9b761e9d29fb64c4cc3eb8092328abf372ac9d5bae5a4a1566dd387d73d188d9c0705dc2",
          "sha256": "67fc7de273669c3a3265b5a8d3f3fa7abd8f941ddc58462b89927afcdc1d5b0a",
          "sha1": "94e3b8a5fdca0682430f6c8c20b791732124d473",
          "md5": "7bdcb268e2c901e939a972d2e21262f1"
        }
      ]
    }
  ]
}
