{
  "formatVersion": "1.1",
  "component": {
    "group": "Component",
    "module": "auto-plugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "novo7h6acfbslf6cq45udvhvvi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "auto-plugin-unspecified.jar",
          "url": "auto-plugin-unspecified.jar",
          "size": 82168,
          "sha512": "1efec0d19e929e7a468e484b35b98a0d484f2284ba9bd9cd6b8ca39110f22f474498e45b9d78631ec4d4d89060b47cfc85f09674874f81b012c0395aee657a89",
          "sha256": "cdd16aca5fc83bcf2f40917a0b8f97d8dfa6c2decc853a01fb1d27091a4e4b1b",
          "sha1": "9b8816b9d43dda6ac035fa1c6400126756dec769",
          "md5": "4b97dcd39bbc89e9a73a783f2cb15aa5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "3.6.3"
          }
        },
        {
          "group": "org.jacoco",
          "module": "org.jacoco.core",
          "version": {
            "requires": "0.8.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "auto-plugin-unspecified.jar",
          "url": "auto-plugin-unspecified.jar",
          "size": 82168,
          "sha512": "1efec0d19e929e7a468e484b35b98a0d484f2284ba9bd9cd6b8ca39110f22f474498e45b9d78631ec4d4d89060b47cfc85f09674874f81b012c0395aee657a89",
          "sha256": "cdd16aca5fc83bcf2f40917a0b8f97d8dfa6c2decc853a01fb1d27091a4e4b1b",
          "sha1": "9b8816b9d43dda6ac035fa1c6400126756dec769",
          "md5": "4b97dcd39bbc89e9a73a783f2cb15aa5"
        }
      ]
    }
  ]
}
