{
  "formatVersion": "1.1",
  "component": {
    "group": "Component",
    "module": "auto-plugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "s2ouohl7sne6lfwxizohcwp3xi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "auto-plugin-unspecified.jar",
          "url": "auto-plugin-unspecified.jar",
          "size": 144589,
          "sha512": "4b7c518c7d4c020110d405a5e0df47447590c4d21a255dab0b73661769c362419069e05b3d46dfe8874756f03df86ba1bb4c16d42e4c4ffa42f7579dc0fae1b6",
          "sha256": "a925da820254e35141642b1f928baa7a268edd9c4b99fb1a16f10c44cbaaf018",
          "sha1": "04f1a0d37b66f27e322b67cd0568a675970d88c2",
          "md5": "140d787009481dd5a4a5d09e397f1b51"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "3.6.3"
          }
        },
        {
          "group": "org.jacoco",
          "module": "org.jacoco.core",
          "version": {
            "requires": "0.8.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "auto-plugin-unspecified.jar",
          "url": "auto-plugin-unspecified.jar",
          "size": 144589,
          "sha512": "4b7c518c7d4c020110d405a5e0df47447590c4d21a255dab0b73661769c362419069e05b3d46dfe8874756f03df86ba1bb4c16d42e4c4ffa42f7579dc0fae1b6",
          "sha256": "a925da820254e35141642b1f928baa7a268edd9c4b99fb1a16f10c44cbaaf018",
          "sha1": "04f1a0d37b66f27e322b67cd0568a675970d88c2",
          "md5": "140d787009481dd5a4a5d09e397f1b51"
        }
      ]
    }
  ]
}
