{
  "formatVersion": "1.1",
  "component": {
    "group": "Component",
    "module": "auto-plugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "tl4cdf6cpjdprigjtvzmbhc74a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "auto-plugin-0.0.13.jar",
          "url": "auto-plugin-0.0.13.jar",
          "size": 146667,
          "sha512": "65835ca360ff3f01b5c4a69ebe09788e40e03c39f7d33c20777371ea5039aad15e5cc8dc1989a8f4e7fd92833c9c5a10672e3758df5eac5b400f92fa8079885d",
          "sha256": "733132d9a65a65c25137806acde36b4921d72288a7dde32486541f5d25b8e0aa",
          "sha1": "9a95b8d1c11d5e07524dbd1805235e61a61dec56",
          "md5": "01e8e8a4b6467561e9f849b47b3a83c7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "auto-plugin-0.0.13.jar",
          "url": "auto-plugin-0.0.13.jar",
          "size": 146667,
          "sha512": "65835ca360ff3f01b5c4a69ebe09788e40e03c39f7d33c20777371ea5039aad15e5cc8dc1989a8f4e7fd92833c9c5a10672e3758df5eac5b400f92fa8079885d",
          "sha256": "733132d9a65a65c25137806acde36b4921d72288a7dde32486541f5d25b8e0aa",
          "sha1": "9a95b8d1c11d5e07524dbd1805235e61a61dec56",
          "md5": "01e8e8a4b6467561e9f849b47b3a83c7"
        }
      ]
    }
  ]
}
